-- Drop os_type column from mobile_products if it exists
ALTER TABLE mobile_products DROP COLUMN IF EXISTS os_type;

-- Add missing columns to mobile_products
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS model_name TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS chipset TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS charging_specs TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS resolution TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS screen_size TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS announced TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS cpu_details TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS gpu_details TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS card_slot BOOLEAN DEFAULT false;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS memory_type TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS display_type TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS display_protection TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS dimensions TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS weight TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS build_material TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS sim_type TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS protection_rating TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS wlan TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS bluetooth TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS nfc BOOLEAN DEFAULT false;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS gps TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS usb_type TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS radio BOOLEAN DEFAULT false;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS infrared BOOLEAN DEFAULT false;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS network_technology TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS network_speed TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS loudspeaker_type TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS audio_jack BOOLEAN DEFAULT false;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS sensors TEXT[];
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS available_colors TEXT[];
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS model_variants TEXT[];
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS bands_2g TEXT[];
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS bands_3g TEXT[];
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS bands_4g TEXT[];
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS bands_5g TEXT[];
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS main_camera_type TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS selfie_camera_type TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS selfie_camera TEXT;
ALTER TABLE mobile_products ADD COLUMN IF NOT EXISTS selfie_camera_video TEXT;

-- Add missing columns to laptops
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS model_name TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS series TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS thickness TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS dimensions TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS weight TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS os_type TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS display_size TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS display_resolution TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS pixel_density TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS display_features TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS refresh_rate TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS graphics TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS graphics_memory TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS clock_speed TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS cache TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS ram_type TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS ram_speed TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS memory_slots TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS expandable_memory TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS ssd_capacity TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS battery_cell TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS battery_type TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS power_supply TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS battery_life TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS wlan TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS wifi_version TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS bluetooth_version TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS hdmi_ports TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS usb_type_c TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS ethernet_ports TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS headphone_jack BOOLEAN DEFAULT false;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS microphone_jack BOOLEAN DEFAULT false;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS webcam BOOLEAN DEFAULT false;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS video_recording TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS audio_solution TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS microphone BOOLEAN DEFAULT false;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS backlit_keyboard TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS face_recognition TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS warranty TEXT;
ALTER TABLE laptops ADD COLUMN IF NOT EXISTS sales_package TEXT;
